### ISSUE TITLE
issues with Makefile/Github

### ISSUE THREAD

**Issue by benkeser** [brkessler99/data_550_final#2]
your current call to `docker run` is not correct. Please review [hints on Canvas](https://canvas.emory.edu/courses/128222/discussion_topics/1034921). 

Also I notice that your github repo does not contain a folder called `report`. You may need to add a `.gitkeep`?

**Comment by benkeser** [comment]
I will regrade when you close this issue.

**Comment by brkessler99** [comment]
added "" around command sub in the makefile, added empty report directory
