### ISSUE TITLE
still having build problems

### ISSUE THREAD

**Issue by benkeser** [brkessler99/data_550_final#3]
still getting an error. did you copy code/04_render.R to the image during build?

![image](https://github.com/brkessler99/data_550_final/assets/17482713/91fdad80-62e5-46f7-a3b2-a03cb6e2b773)

**Comment by benkeser** [comment]
I think maybe you didn't push the most recent build to docker hub?

**Comment by brkessler99** [comment]
rebuilt the image and pushed to DockerHub without changing the name
